[Plot.0]
field_selected = 0
cmap = "Jet"
vmax = 1.0
vmin = 0.0
log = false
type = "Pcolor2d"
ID = 0

[Plot.2]
field_selected = 0
cmap = ""
vmax = 1.0
vmin = 0.0
log = false
type = "Scatter2d"
ID = 2

[Plot]
npanels = 2
