version: "3"
services:
  nttiny:
    image: nttiny
    container_name: nttiny
    build:
      context: .
      args:
        USERNAME: $USER
    volumes:
      - type: bind
        source: ../
        target: /home/$USER/nttiny
